// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siwlianoxnpmavinketo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpd2xpYW5veG5wbWF2aW5rZXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NTc3NzcsImV4cCI6MjA1MjMzMzc3N30.J-vS3MXgPgNlrkiqzQ5aXkp8g5j26LrYRkOe0zz4J4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);